--alter table OMEGA_TEST_DB.ITD_SCHEMACHANGE_DEMO.RIGDIG_ACTIVITY_CURRENT add column new_column varchar(231);

call OMEGA_TEST_DB.ITD_SCHEMACHANGE_DEMO.SafeAddColumn('OMEGA_TEST_DB.ITD_SCHEMACHANGE_DEMO.RIGDIG_ACTIVITY_CURRENT', 'new_column', 'varchar(12312313)');

alter table OMEGA_TEST_DB.ITD_SCHEMACHANGE_DEMO.RIGDIG_ACTIVITY_CURRENT drop column new_column; 