create TABLE if not exists ITD_SCHEMACHANGE_DEMO.RIGDIG_LINEAGE_HISTORY (
	RPT_YR NUMBER(4,0),
	RPT_MONTH NUMBER(2,0),
	RRID NUMBER(10,0),
	EQT_VIN_SN VARCHAR(100),
	EQT_MAKE VARCHAR(50),
	EQT_MODEL_YEAR VARCHAR(4),
	EQT_GVWR_CLASS VARCHAR(50),
	EQT_DOMRA_ENT DATE,
	EQT_DOMRA_VIN DATE,
	EQT_OUT_OF_FLEET_FLAG NUMBER(10,0)
);