name: FindReplace
on: 
  pull_request:
    branches:
      -TEST
      
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "OMEGA_PROD_DB."
          replace: "OMEGA_TEST_DB."
          regex: false
